import { stringify } from "yaml"
import type { AppConfig } from "./config"

const HEADER = "# GENERATED by `npm run setup` from cameras.yml — do not edit by hand.\n"

function go2rtcPortEnv(name: "API" | "RTSP" | "WEBRTC", fallback: string): string {
  return process.env[`GO2RTC_${name}_PORT`] ?? fallback
}

export function renderGo2rtc(config: AppConfig): string {
  const streams: Record<string, string[]> = {}
  const preload: Record<string, null> = {}
  for (const cam of config.cameras) {
    if (!cam.enabled) continue
    streams[cam.id] = [`${cam.url}#backchannel=0`]
    // Keep upstream producers warm so 24/7 recording does not depend on a browser viewer.
    preload[cam.id] = null
  }
  const doc = {
    api: { listen: `:${go2rtcPortEnv("API", "1984")}` },
    rtsp: { listen: `:${go2rtcPortEnv("RTSP", "8554")}` },
    webrtc: {
      listen: `:${go2rtcPortEnv("WEBRTC", "8555")}`,
      candidates: [config.webrtcCandidate],
    },
    preload,
    streams,
  }
  return HEADER + stringify(doc, { defaultStringType: "QUOTE_DOUBLE", defaultKeyType: "PLAIN" })
}

export function renderClientCameras(config: AppConfig): string {
  const list = config.cameras
    .filter((cam) => cam.enabled)
    .map((cam) => ({ id: cam.id, name: cam.name }))
  return JSON.stringify(list, null, 2) + "\n"
}
