import { stringify } from "yaml"
import type { AppConfig } from "./config"

const HEADER = "# GENERATED by `npm run sync-cameras` from cameras.yml — do not edit by hand.\n"

export function renderGo2rtc(config: AppConfig): string {
  const streams: Record<string, string[]> = {}
  for (const cam of config.cameras) {
    if (cam.enabled) streams[cam.id] = [cam.url]
  }
  const doc = {
    api: { listen: ":1984" },
    rtsp: { listen: ":8554" },
    webrtc: { listen: ":8555", candidates: [config.webrtcCandidate] },
    streams,
  }
  return HEADER + stringify(doc, { defaultStringType: "QUOTE_DOUBLE", defaultKeyType: "PLAIN" })
}

export function renderClientCameras(config: AppConfig): string {
  const list = config.cameras
    .filter((cam) => cam.enabled)
    .map((cam) => ({ id: cam.id, name: cam.name }))
  return JSON.stringify(list, null, 2) + "\n"
}
